<a href="https://colab.research.google.com/github/bharathyadav524/AD-HOC-Insights-Consumer-Goods-/blob/main/DEVA_SIR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

DAY1

# What is Data Analysis?

Data Analysis means studying data to find useful information.

# Why Data Analysis?

To make better decisions

To find patterns and trends

To solve problems

To improve business performance

To understand customers

To plan for the future

🤖 AI (Artificial Intelligence)

AI means making machines think and act like humans.

🤖 ML (Machine Learning)

ML is a part of AI where machines learn from data and improve on their own.

🤖 DL (Deep Learning)

DL is a type of ML that uses brain-like structures (neural networks) to learn from large amounts of data.

#🛠️ What is Feature Engineering?

Feature Engineering means creating better input data (features) to help a machine learning model learn more accurately.

Simple Example:

If you're predicting house prices:

You have features like size, location, and number of rooms.

You can create a new feature like "price per square foot" — that’s feature engineering!

In short:

Better features = Better model performance ✅

Data Analyst = What happened? Why?

Data Scientist = What will happen? How can we predict it?

#WHAT IS NUMPY ?

NUMPY IS A PYTHON LIBRARY USED FOR WORKING WITH ARRAYS

NUMPY WAS CREATED IN 2005 BY TRAVIS OLIPHANT

NUMPY STANDS FOR NUMERICAL PYTHON


#WHY NUMPY ?

NUMPY PROVIDES ARRAY OBJECTS TO WORK WITH COMPUTATION PROBLEMS AND IT IS 50X FASTER THAN LIST

In [ ]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
arr = np.array([1,2,3,4])
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
import array

arr = array.array('i',[1])
print(arr)
print(type(arr))

array('i', [1])


In [ ]:
arr_list = np.array([1,2,4,5])
arr_tuple = np.array((10,20,40,50))
arr_str = np.array("Bharath Kumar")
arr_set = np.array({10,20,40,50})
arr_dict = np.array({"a":10,"b":20})

dtype --> IT SHOWS WHAT KIND OF DATA WE ARE STORED

In [ ]:
print("list : ",arr_list.dtype) #integer for int64
print("tuple : ",arr_tuple.dtype)
print("string : ",arr_str.dtype) #str for <u13
print("set : ",arr_set.dtype) #set for object
print("dict : ",arr_dict.dtype)#dictionary for object

list :  int64
tuple :  int64
string :  <U13
set :  object
dict :  object


ndim --> it Shows Whats the dimension of Our Array

In [ ]:
print(f"array List Values : {arr_list.ndim}")
print(f"arary tuple Values: {arr_tuple.ndim}")
print(f"array string Values : {arr_str.ndim}")
print(f"array Set Values : {arr_set.ndim}")
print(f"array dict Values : {arr_dict.ndim}")

array List Values : 1
arary tuple Values: 1
array string Values : 0
array Set Values : 0
array dict Values : 0


HIERARCHY

bool<int<float<complex<str<object

1D --> VECTOR

In [ ]:
import numpy as np
arr_bool = np.array([True,False])
print(arr_bool)
print(arr_bool.dtype)

[ True False]
bool


In [ ]:
arr_int = np.array([True,False,10])
print(arr_int)
print(arr_int.dtype)

[ 1  0 10]
int64


In [ ]:
arr_float = np.array([True,False,10,2.2])
print(arr_float)
print(arr_float.dtype)

[ 1.   0.  10.   2.2]
float64


In [ ]:
arr_complex = np.array([True,False,10,4.3,3+2j])
print(arr_complex)
print(arr_complex.dtype)

[ 1. +0.j  0. +0.j 10. +0.j  4.3+0.j  3. +2.j]
complex128


In [ ]:
arr_str = np.array([True,False,10,2.2,3+3j,"Hello"])
print(arr_str)
print(arr_str.dtype)

['True' 'False' '10' '2.2' '(3+3j)' 'Hello']
<U64


In [ ]:
arr_str = np.array([True,False,10,2.2,3+3j,"Hello"])
print(arr_str.shape) #for single or Scalar array shape will give you no of Elements Present in collection we passed

(6,)


NEXT IT WILL CONSIDER AS OBJECT FOR COLLECTIONS

2D ARRAY  -->Matrix

In [ ]:
arr_2d = np.array([[10,20,30],[40,50,60]])
print(arr_2d)
print(arr_2d.dtype)

[[10 20 30]
 [40 50 60]]
int64


In [ ]:
arr_2d_str = np.array([["2d","Array"],["Creation","Now"]])
print(arr_2d_str)

[['2d' 'Array']
 ['Creation' 'Now']]


In [ ]:
arr_2d = np.array([[10,20,30],[40,50,60]])
print(arr_2d.ndim)

2


In [ ]:
arr_2d = np.array([[10,20,30],[40,50,60]])
print(arr_2d.shape)

(2, 3)


3D --> TENSOR or DEPTH

In [ ]:
lst = [[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]]
arr = np.array(lst)
print(arr)
print(arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


In [ ]:
lst = [[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]]
arr = np.array(lst)
print(arr.shape)

(2, 2, 3)


dtype,ndim,shape

shape
1D retruns no of elements inside the collection for single or 1d array

2D return (rows,columns)

3D return (depth,rows,columns)


In [ ]:
import numpy as np
lst = [[[10,20,30],[10,20,30],[30,30,40]]]
arr = np.array(lst)
print(arr)


[[[10 20 30]
  [10 20 30]
  [30 30 40]]]


In [ ]:
print(arr.dtype)

int64


ndim -->(depth,row,column)

In [ ]:
print(arr.ndim)

3


In [ ]:
print(arr.shape)

(1, 3, 3)


In [ ]:
lst = [10,20,30,40,50,60,70,80,90]
arr = np.array(lst)
print(arr.reshape(3,3))

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [ ]:
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

int64
1
(9,)


In [ ]:
# 1D
arr_1d = np.array([1,2,3,4])
print(arr_1d.ndim)
print(arr_1d.shape)

1
(4,)


In [ ]:
# 2D
arr_1d = np.array([[1,2,3],[4,5,6]])
print(arr_1d.ndim)
print(arr_1d.shape)

2
(2, 3)


In [ ]:
# 3D
arr_1d = np.array([[1,2,3,4,5]])
print(arr_1d.ndim)
print(arr_1d.shape)

2
(1, 5)


In [ ]:
lst = [[[1],[3],[2]],[[1],[3],[2]]]

arr = np.array(lst)
print(arr)
print(arr.shape)

[[[1]
  [3]
  [2]]

 [[1]
  [3]
  [2]]]
(2, 3, 1)


In [ ]:
lst = [[[1,2,3],[3,3,4],[2,2,3]],[[1,2,3],[3,2,3],[2,3,2]]]
arr = np.array(lst)
print(arr)
print(arr.shape)

[[[1 2 3]
  [3 3 4]
  [2 2 3]]

 [[1 2 3]
  [3 2 3]
  [2 3 2]]]
(2, 3, 3)


In [ ]:
# 1,3,3
lst = [[[2,3,4],[3,3,3],[3,4,5]]]
arr = np.array(lst)
print(arr.shape)

(1, 3, 3)


#IN BUILT FUNCTIONS

np.zeros((depth,row,col),dtype=int)

create an array filled with zeros

In [ ]:
# 1D
arr = np.zeros((3),dtype=int)
print(arr)

[0 0 0]


In [ ]:
# 2D
arr = np.zeros((3,4),dtype=int)
print(arr)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
# 3D
arr = np.zeros((2,3,4),dtype=str)
print(arr)

[[['' '' '' '']
  ['' '' '' '']
  ['' '' '' '']]

 [['' '' '' '']
  ['' '' '' '']
  ['' '' '' '']]]


np.ones((depth,row,col),dtype=int)

create an array filled with ones

In [ ]:
# 1D
arr = np.ones((3),dtype=int)
print(arr)

[1 1 1]


In [ ]:
# 2D
arr = np.ones((3,4),dtype=int)
print(arr)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
# 3D
arr = np.ones((2,3,4),dtype=str)
print(arr)

[[['1' '1' '1' '1']
  ['1' '1' '1' '1']
  ['1' '1' '1' '1']]

 [['1' '1' '1' '1']
  ['1' '1' '1' '1']
  ['1' '1' '1' '1']]]


arange --.

In [ ]:
arr = np.arange(1,11,dtype=int)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
arr = np.linspace(1,10,3,dtype=int)
print(arr)

[ 1  5 10]


In [ ]:
arr = np.linspace(1,10,5)
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
arr = np.empty((2,3,3),dtype=int)
print(arr)

[[[1 2 3]
  [3 3 4]
  [2 2 3]]

 [[1 2 3]
  [3 2 3]
  [2 3 2]]]


In [ ]:
arr = np.eye(2,3,2,dtype=int)
print(arr)

[[0 0 1]
 [0 0 0]]


(2, 4, 3)

(3, 3, 3)

(4, 2, 5)

(3, 3, 4)

(2, 3, 3)

(2, 3, 4)

(3, 2, 2)

(2, 3, 3)

(3, 4, 2)

In [ ]:
import numpy as np
lst = [
    [[1,2],[2,3],[4,5],[5,6]],
    [[1,2],[2,3],[4,5],[5,6]],
    [[1,2],[2,3],[4,5],[5,6]]
]
arr = np.array(lst)
print(arr.shape)

(3, 4, 2)


In [ ]:
lst = [
    [[2,3,4],[3,4,4],[4,3,4]],
    [[2,3,4],[3,4,4],[4,3,4]],
    [[2,3,4],[3,4,4],[4,3,4]]

]

arr = np.array(lst)
print(arr.shape)

(3, 3, 3)


In [ ]:
lst =[
    [[1,2,3,4,5],[1,2,3,5,6]],
    [[1,2,3,4,5],[1,2,3,4,3]]
]
arr = np.array(lst)
print(arr.shape)

(2, 2, 5)


In [ ]:
import numpy as np
# (3, 3, 4)
lst = [
    [[2,3,5,6],[2,4,2,2],[2,2,2,1]],
    [[2,3,5,6],[2,4,2,2],[2,2,2,1]],
    [[2,3,5,6],[2,4,2,2],[2,2,2,1]]

]

arr = np.array(lst)
print(arr.shape)

(3, 3, 4)


In [ ]:
# (2, 3, 4)
lst = [
    [[2,3,5,3],[2,2,4,2],[2,4,2,4]],
    [[2,3,5,3],[2,2,4,2],[2,4,2,4]]
]

arr = np.array(lst)
print(arr.shape)

(2, 3, 4)


#np.linspace

Create an array with a specified number of equally spaced elements between a given range


np.linspace(start value , end value , step or num = value)

here num represents the specified sub parts you have to devided

np.eye(rows,columns,step value) --> creates an identity matrix

np.empty() --> creates an empty array without initializing values

np.zeros()

np.ones()

np.arange()

In [ ]:
arr = np.eye(3,4,1)
print(arr)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


ARRAY SHAPE AND STRUCTURE BUILTIN FUNCtiONS

reshape() --> change the shape or array

np.reshape(arr,(row,col))

or

arr.reshape(row,col)

In [ ]:
arr = np.arange(1,13)
print(arr)

#reshape function
print()
print(arr.reshape(3,4))

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
arr = np.linspace(1,20,6)
print(arr.reshape(2,3))

[[ 1.   4.8  8.6]
 [12.4 16.2 20. ]]


In [ ]:
lst = [1,2,3,4,5,6,7,8,9,10,11,12]
arr = np.reshape(lst,(4,3))
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
int64
(4, 3)
2


[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
arr = np.arange(2,13,2)
print(arr.reshape(3,2))
# or
print()
print(arr.reshape(2,3))
print()
print(arr.reshape(6,1))
print()
print(arr.reshape(1,6))



[[ 2  4]
 [ 6  8]
 [10 12]]

[[ 2  4  6]
 [ 8 10 12]]

[[ 2]
 [ 4]
 [ 6]
 [ 8]
 [10]
 [12]]

[[ 2  4  6  8 10 12]]


In [ ]:
arr = np.linspace(1,13,13)
print(arr.reshape(13,1))

[[ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 6.]
 [ 7.]
 [ 8.]
 [ 9.]
 [10.]
 [11.]
 [12.]
 [13.]]


np.ravel(lst) --> convert to 1D array

In [ ]:
arr = np.arange(2,21,2)
print(arr)
print()
arr_re = arr.reshape(5,2)
print(arr_re)

re = np.reshape(arr_re,(-1))
print(re)
# print(arr_re.ravel())


[ 2  4  6  8 10 12 14 16 18 20]

[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]
 [18 20]]
[ 2  4  6  8 10 12 14 16 18 20]


ARRAY MATHEMATICAL FUNCTIONS

In [ ]:
arr = np.arange(1,100)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [ ]:
print("Sum : ",np.sum(arr))
print("Mean : ",np.mean(arr))
print("Median : ",np.median(arr))
print("STANDARD DEVIATION : ",np.std(arr))
print("Min Value :  ",np.min(arr))
print("Max Value : ",np.max(arr))


Sum :  4950
Mean :  50.0
Median :  50.0
STANDARD DEVIATION :  28.577380332470412
Min Value :   1
Max Value :  99


#RANDOM FUNCTIONS


np.random.rand(depth,row,col)

create array with random value between 0 to 1

In [ ]:
arr = np.random.rand(2,2,2)
print(arr)

[[[0.71004705 0.1567029 ]
  [0.70976634 0.89330406]]

 [[0.74803674 0.51096402]
  [0.24368216 0.83270147]]]


np.random.randint(start,end , size = (depth , row , col),dtype='int32')

In [ ]:
arr = np.random.randint(1,10,(3,3),dtype='int32')
print(arr)

[[4 5 1]
 [8 1 7]
 [1 1 3]]


np.random.randn(shape,dtype)

In [ ]:
arr = np.random.randn(3,3,3)
print(arr)

[[[ 0.39574205 -1.84140499 -1.3701174 ]
  [-0.41228283  0.01499298  0.17058564]
  [ 0.11133941  0.19216415 -1.47723006]]

 [[-0.32835615 -0.12166958  1.03037152]
  [ 0.92505253 -0.92619479 -1.80410418]
  [-0.46830597 -0.49358143  0.55343158]]

 [[ 0.4165454  -0.6546097  -0.94340279]
  [-1.14202307  0.85577213  1.37468965]
  [ 0.19911951 -1.69878233 -1.5268228 ]]]


ACCESSING AND MODIFYING ELEMENTS IN NUMPY

In [ ]:
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
print(arr[3])

4


In [ ]:
arr[3]=11
print(arr[3])
print(arr)

11
[ 1  2  3 11  5  6  7  8  9 10]


2D Array -- arr[row_index , col_index]

In [ ]:
arr = np.arange(1,9)
# print(arr)
arr = arr.reshape(2,4)
# print(arr)
print(arr[1,2])

7


In [ ]:
arr[1,2]=70
print(arr[1,2])
print(arr )

70
[[ 1  2  3  4]
 [ 5  6 70  8]]


3d -->
arr[depth_index , row_index , col_index]

In [ ]:
arr = np.arange(1,46)
arr = arr.reshape(3,3,5)
print(arr)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]

 [[31 32 33 34 35]
  [36 37 38 39 40]
  [41 42 43 44 45]]]


In [ ]:
print(arr[2,2,3])

44


In [ ]:
arr[2,2,3]=440
print(arr)

[[[  1   2   3   4   5]
  [  6   7   8   9  10]
  [ 11  12  13  14  15]]

 [[ 16  17  18  19  20]
  [ 21  22  23  24  25]
  [ 26  27  28  29  30]]

 [[ 31  32  33  34  35]
  [ 36  37  38  39  40]
  [ 41  42  43 440  45]]]


In [ ]:
import numpy as np

Create a 1D NumPy array with values from o to 9.

What is the shape and data type of this array: np.array([5, 10, 15, 20])?

Convert a Python list [1, 2, 3, 4] into a NumPy array.

How do you access the third element of a 1D NumPy array?

Create a 1D array of 10 zeros and change the 5th element to 100.

Create a 1D array with 20 random integers between 1 and 100 and find the mhaximum and minimum values.

Create a 2x3 NumPy array with values from 1 to 6.

How do you access the element in the second row, third column of a 2D array?

What is the shape of the following array: np.array([[1,2],[3,4],[5,6]])?

Create a 4X4 array of all zeros and replace the diagonal elements with 1.

Create a 3x3 identity matrix using NumPy.

Create a 3D NumPy array with shape (2, 3, 4) filled with zeros.

What is the shape of the array: np.ones((2,2,2))?

How many dimensions does a 3D array have?

Create agD array of shape (2,3,3) filled with random numbers between o and 1.

In [ ]:
# 1
arr = np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [ ]:
#2
arr = np.array([5,10,15,20])
print(arr.shape)
print(arr.dtype)

(4,)
int64


In [ ]:
#3
lst = [1,2,3,4]
arr = np.array(lst)
print(arr)

[1 2 3 4]


In [ ]:
#4
lst = [1,2,3,4]
arr = np.array(lst)
print(arr[2])

3


In [ ]:
#5
arr = np.zeros(10,dtype=int)
arr[4]=100
print(arr)

[  0   0   0   0 100   0   0   0   0   0]


In [ ]:
#6
arr = np.random.randint(1,100,(5,7),dtype=int)
print(arr)
max_val = np.max(arr)
print(max_val)
min_val = np.min(arr)
print(min_val)

[[39 89 88 11 45 46 39]
 [72 14 86 71 89 92 40]
 [89 60 71 33 75 20 65]
 [ 5 24 45  3 37 66 45]
 [60 72 54 85 39 64 24]]
92
3


In [ ]:
#7
arr = np.arange(1,7)
arr = arr.reshape(2,3)
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
#8
arr = np.arange(1,9)
arr = arr.reshape(2,4)
print(arr)
print(arr[1,2])

[[1 2 3 4]
 [5 6 7 8]]
7


In [ ]:
#9
arr = np.array([[1,2],[3,4],[5,6]])
print(arr.shape)

(3, 2)


In [ ]:
#10
arr = np.eye(4,4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#11
arr = np.eye(3,3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#11
import numpy as np
arr = np.zeros((4, 4))
print(arr)
print()
np.fill_diagonal(arr, 1)
print(arr)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#12
arr = np.zeros((2,3,4))
print(arr)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [ ]:
#13
arr = np.ones((2,2,2))
print(arr)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [ ]:
#14
# 3d array having 3 dimensions
arr = np.random.rand(2,3,3)
print(arr.ndim)


3


In [ ]:
#15
arr = np.random.rand(2,3,3)
print(arr)

[[[0.09502405 0.50501275 0.98358137]
  [0.87589208 0.04452632 0.69777196]
  [0.61325464 0.26359234 0.06154645]]

 [[0.9414336  0.32768407 0.62486561]
  [0.03121848 0.12718223 0.22508011]
  [0.45445655 0.33276268 0.02979135]]]


In [ ]:
arr = np.random.randint(1,21,(4,5),dtype=int)
print(arr)

[[13  6  6  7  9]
 [11 11  6  7 13]
 [19  1 17 20 11]
 [ 2  6 12  4 15]]


In [ ]:
arr = np.random.randint(1,21,size=(20),dtype=int)
arr = arr.reshape(4,5)
print(arr)

[[ 8 10 11  9 10]
 [20  8  2 11  7]
 [13 11 10 18  9]
 [10  6  9  1  5]]


In [ ]:
arr = np.random.randn(4,5)
print(arr)

[[ 0.11558975 -0.6461415  -0.15146911  0.26484791 -1.06460285]
 [ 1.15846814  0.51075296  1.49992743  0.45711351 -1.26604357]
 [-0.61212483 -0.25293196 -1.53306285  0.27983224  1.30283782]
 [-0.63971166  0.31334902 -0.46589261 -0.33553253 -1.19735219]]


In [ ]:
import numpy as np
arr = np.arange(1,27,dtype=int)
arr = arr.reshape(1,2,13)
print(arr)
print()
# arr = arr.reshape(1,13,2)
# print(arr)

[[[ 1  2  3  4  5  6  7  8  9 10 11 12 13]
  [14 15 16 17 18 19 20 21 22 23 24 25 26]]]



In [ ]:
arr = np.arange(1,39)
arr = arr.reshape(1,2,19)
# print(arr)

# arr = arr.reshape(2,19,1)
# print(arr)

# arr = arr.reshape(1,38,1)
# print(arr)

# arr = arr.reshape(1,1,38)
# print(arr)

arr = np.ravel(arr)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38]


In [ ]:
arr = np.random.rand(2,3,4)
print(arr)

[[[0.22840535 0.61550644 0.20574953 0.36569382]
  [0.22495417 0.65100101 0.82163926 0.84783991]
  [0.49161062 0.20417863 0.5170372  0.2309059 ]]

 [[0.73547961 0.49849009 0.64228993 0.67407941]
  [0.18440051 0.04270051 0.4963048  0.57120583]
  [0.58770611 0.4330088  0.93856313 0.63732269]]]


In [ ]:
arr = np.random.randn(2,3,4)
print(arr)

[[[ 0.22749809 -1.07553706  1.00915769 -0.65581436]
  [-0.59815292  0.23019056 -1.33808314 -0.68249104]
  [-0.44931812 -0.95194115 -0.28921209 -0.18099742]]

 [[-1.08617918  1.08920688 -0.51165615  0.51187882]
  [-0.6227919   0.22044185  0.55701901  1.74519414]
  [ 1.54768096 -1.99380569  0.4825744  -0.79823891]]]


In [ ]:
arr = np.random.randint(1,11)
print(arr)

8


In [ ]:
arr = np.zeros((3,3))
print(arr)
np.fill_diagonal(arr,1)
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#accessing and modifying the array
arr = np.eye(5,5,dtype=int)
print(arr)
print()
print("Middle One : ",arr[2,2])
print()
arr[2,2] = 100
print(arr)
print()
print("Middle One : ",arr[2,2])

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]

Middle One :  1

[[  1   0   0   0   0]
 [  0   1   0   0   0]
 [  0   0 100   0   0]
 [  0   0   0   1   0]
 [  0   0   0   0   1]]

Middle One :  100


In [ ]:
arr = np.arange(1,21)
arr = arr.reshape(4,5)
print(arr)
print()
print("Middle One : ",arr[2,2])
print()
arr[2,2] = 130
print(arr)
print()
print("Middle One : ",arr[2,2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Middle One :  13

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12 130  14  15]
 [ 16  17  18  19  20]]

Middle One :  130


In [ ]:
arr = np.arange(1,17)
arr = arr.reshape(2,2,4)
print(arr)
print()
print("Middle One : ",arr[1,0,2])
arr[1,0,2]=110
print(arr)
print()
print("Middle One : ",arr[1,0,2])

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]

Middle One :  11
[[[  1   2   3   4]
  [  5   6   7   8]]

 [[  9  10 110  12]
  [ 13  14  15  16]]]

Middle One :  110


#Copy -->Shallow Copy and DeepCopy

In [ ]:
arr =np.array([[1,2,3,4],
      [5,6,7,8]])

arr1 = arr.view()
arr[1,1]=60
print(arr)
print()
print(arr1)

[[ 1  2  3  4]
 [ 5 60  7  8]]

[[ 1  2  3  4]
 [ 5 60  7  8]]


In [ ]:
arr =np.array([[1,2,3,4],
      [5,6,7,8]])

arr1 = arr.copy()
arr[1,1]=60
print(arr)
print()
print(arr1)

[[ 1  2  3  4]
 [ 5 60  7  8]]

[[1 2 3 4]
 [5 6 7 8]]


#SLICING

1D --> ARRAY

In [ ]:
arr = np.arange(1,8)
print(arr[2:6:1])

[3 4 5 6]


In [ ]:
arr[2:4]

array([3, 4])

2D --> ARRAY

In [ ]:
arr = np.arange(1,11)
arr = arr.reshape(2,5)
print(arr)
print()
print(arr[::,3::])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[[ 4  5]
 [ 9 10]]


In [ ]:
arr = np.arange(1,21)
arr = arr.reshape(4,5)
print(arr)
print()
print(arr[::,3::])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]]


In [ ]:
arr = np.arange(1,31)
arr = arr.reshape(5,6)
# print(arr[::,3::])
print(arr)
print()
print(arr[2:4,2:5])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]

[[15 16 17]
 [21 22 23]]


3D --> ARRAY

In [2]:
import numpy as np
arr = np.arange(1,21)
arr = arr.reshape(2,2,5)
print(arr)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


In [6]:
#fetch the 14 element
print(arr[1:2,0:1,3:4])

[[[14]]]


In [5]:
#fetch the 5,10
print(arr[0:1,0:1,3:5])

[[[4 5]]]


In [9]:
#fetch the 19
print(arr[1:2,1:2,3:4])

[[[19]]]


In [11]:
#fetch the 13,18
print(arr[1:2,0:2,2:3])

[[[13]
  [18]]]
